data_sources:
  api_keys:
    alpaca:
      api_key: PKKWCPVCUKJJYS7HYL1C
      base_url: https://paper-api.alpaca.markets
      secret_key: VC7dDPb8KX5dWOLF0tFGySVwPBL8OAQLPcc10FXM
    alpha_vantage: YOUR_API_KEY
    ib:
      client_id: 2
      host: 127.0.0.1
      port: 4001
  backup: alpha_vantage
  primary: alpaca
email:
  password: your_app_password
  recipients:
  - trader@example.com
  smtp_port: 587
  smtp_server: smtp.gmail.com
  username: your_email@gmail.com
monitoring:
  backup_interval: 1800
  enable_email_alerts: false
  enable_slack_alerts: false
  performance_report_interval: 3600
  save_trades_to_db: true
risk_management:
  max_daily_loss: 5000.0
  max_daily_trades: 100
  max_leverage: 2.0
  max_portfolio_risk: 0.02
  max_position_value: 50000.0
  max_symbol_exposure: 20000.0
  stop_loss_pct: 0.05
  take_profit_pct: 0.1
signal_aggregation:
  method: weighted_average
  min_confidence_level: MEDIUM
  min_signal_strength: 0.3
slack:
  channel: '#trading-alerts'
  webhook_url: https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
strategies:
  breakout:
    enabled: true
    parameters:
      base_position_size: 150
      max_position_size: 600
    weight: 1.2
  mean_reversion:
    enabled: true
    parameters:
      base_position_size: 100
      max_position_size: 300
    weight: 0.8
  ml_prediction:
    enabled: false
    parameters:
      base_position_size: 100
      max_position_size: 400
    weight: 0.9
  momentum:
    enabled: true
    parameters:
      base_position_size: 100
      max_position_size: 500
    weight: 1.0
trading:
  data_update_interval: 60
  initial_capital: 100000.0
  mode: live
  signal_generation_interval: 300
  symbols:
  - AAPL
  - GOOGL
  - MSFT
  - TSLA
  - AMZN
  trading_hours:
    end: '16:00'
    start: 09:30
    timezone: US/Eastern
